
let CURRENTFRAME = 0;
const FPS = 30;

let currentMousePos = new Victor(0, 0);

const atoms = {
    hydrogen: {
        symbol: 'H',
        valence: 1,
        color: '#ffffff',
    },
    carbon: {
        symbol: 'C',
        valence: 4,
        color: '#000000',
    },
    nitrogen: {
        symbol: 'N',
        valence: 3,
        color: '#3434d5ff',
    },
    oxygen: {
        symbol: 'O',
        valence: 2,
        color: '#c41313ff',
    },
    sodium: {
        symbol: 'Na',
        valence: 7,
    },
    phosphorus: {
        symbol: 'P',
        valence: 3
    },
    chlorine: {
        symbol: 'Cl',
        valence: 1,
    },
    potassium: {
        symbol: 'K',
        valence: 17,
    },
};





// I got this function from a Medium article; https://colton-shawn-oconnor.medium.com/changing-text-color-based-on-the-background-in-javascript-947bf9bc136b
function getBrightness(r, g, b) {
    return (r * 299 + g * 587 + b * 114) / 1000;
}

// this particular function was generated by Gemini :sob: nothing else is though
// I did add the part accounting for alpha values myself
function RGBFromHex(hex) {
    // Remove '#' if present
    hex = hex.startsWith('#') ? hex.slice(1) : hex;

    // Handle shorthand hex codes (e.g., #FFF)
    if (hex.length === 3) {
        hex = hex[0] + hex[0] + hex[1] + hex[1] + hex[2] + hex[2];
    }

    // Ensure it's a valid 6-digit hex code
    if (!/^[0-9A-Fa-f]{6}$/.test(hex)) {
        console.error("Invalid hex code:", hex);
        return null;
    }
    
    
    const r = parseInt(hex.slice(0, 2), 16);
    const g = parseInt(hex.slice(2, 4), 16);
    const b = parseInt(hex.slice(4, 6), 16);

    const a = (/^[0-9A-Fa-f]{8}$/.test(hex)) ? parseInt(hex.slice(6, 8), 16) : 255;

    return { r, g, b, a };
}

function getTextColorFromBG(hex) {
    const rgb = RGBFromHex(hex);
    const br = getBrightness(rgb.r, rgb.g, rgb.b);

    return (br >= 150) ? '#000000' : '#FFFFFF';
}