const subscriptMap = {
    '0': '₀',
    '1': '₁',
    '2': '₂',
    '3': '₃',
    '4': '₄',
    '5': '₅',
    '6': '₆',
    '7': '₇',
    '8': '₈',
    '9': '₉'
};
const superscriptMap = {
    '0': '⁰',
    '1': '¹',
    '2': '²',
    '3': '³',
    '4': '⁴',
    '5': '⁵',
    '6': '⁶',
    '7': '⁷',
    '8': '⁸',
    '9': '⁹'
};
const toSubscript = (n) => String(n).split('').map(d => subscriptMap[d]).join('');
const toSuperscript = (n) => String(n).split('').map(d => superscriptMap[d]).join('');

/**
 * @typedef {object} RGBA
 * @property {number} r
 * @property {number} g
 * @property {number} b
 * @property {number} a
 */

// this particular function was generated by Gemini :sob: nothing else is though
// I did add the part accounting for alpha values myself
/** @param {string} hexcode @returns {RGBA} */
function RGBFromHex(hexcode) {
    // Remove '#' if present
    let hex = hexcode.startsWith('#') ? hexcode.slice(1) : hexcode;

    // Handle shorthand hex
    if (hex.length === 3) {
        hex = hex[0] + hex[0] + hex[1] + hex[1] + hex[2] + hex[2];
    }

    // only 6- or 8-digit hex codes allowed
    if (!/^[0-9A-Fa-f]{6}$/.test(hex) && !/^[0-9A-Fa-f]{8}$/.test(hex)) {
        console.warn("Invalid hex code:", hex);
        return null;
    }
    
    
    const r = parseInt(hex.slice(0, 2), 16);
    const g = parseInt(hex.slice(2, 4), 16);
    const b = parseInt(hex.slice(4, 6), 16);

    const a = (/^[0-9A-Fa-f]{8}$/.test(hex)) ? parseInt(hex.slice(6, 8), 16) : 255;

    return { r, g, b, a };
}

function hexFromRGB(r, g, b, a = 255) {
    const rhex = r.toString(16).padStart(2, '0');
    const ghex = g.toString(16).padStart(2, '0');
    const bhex = b.toString(16).padStart(2, '0');
    const ahex = a.toString(16).padStart(2, '0');
    return '#' + rhex + ghex + bhex + ahex;
}

/** @param {string} hex @param {number} darkFactor @returns {string} */
function darkenColor(hex, darkFactor) {
    const rgb = RGBFromHex(hex);
    return hexFromRGB(...Object.values(rgb).map(v => Math.round(v * darkFactor)));
}

// I got this function from a Medium article; https://colton-shawn-oconnor.medium.com/changing-text-color-based-on-the-background-in-javascript-947bf9bc136b
function getBrightness(r, g, b) {
    return (r * 299 + g * 587 + b * 114) / 1000;
}

function getTextColorFromBG(hex) {
    const rgb = RGBFromHex(hex);
    const br = getBrightness(rgb.r, rgb.g, rgb.b);

    return (br >= 150) ? '#000000' : '#FFFFFF';
}

function toTitle(str) {
    const check = /[\s\d]/g;
    
    let amendee = str.split(check).map(str => str.charAt(0).toUpperCase() + str.slice(1)).join('').replaceAll('_', ' ');
    let i = 0;
    for (let ii = 0; ii < str.length; ii++) {
        if (check.test(str[ii])) amendee = amendee.slice(0, ii + i) + str[ii] + amendee.slice(ii + i);
        else continue;

        i++;
    }
    return amendee;
}